import { Inter } from "next/font/google";
import "./globals.css";
import Loading from "./loading.js";
import React, { Suspense } from "react"; // Import Suspense from React
import CustomLayout from "@/components/customLayout/index"; // Ensure CustomLayout is imported
import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
        <html lang="en">
        <body className={inter.className}>
          <Suspense fallback={<Loading />}>
            <CustomLayout children={children} />
          </Suspense>
        </body>
      </html>
    </ClerkProvider>
  );
}
